"""Reference path abstraction for Frenet ↔ Cartesian transforms.

A reference path is a smooth centerline parameterized by arc length s.
It provides:
  - evaluate(s) → (x_r, y_r, θ_r, κ_r)     path geometry
  - frenet_to_cartesian(s, d) → (x, y)      for obstacle checking
"""

from __future__ import annotations

import jax.numpy as jnp


class ReferencePath:
    """Abstract reference path: arc-length-parameterized smooth centerline."""

    def evaluate(self, s: jnp.ndarray) -> tuple[jnp.ndarray, jnp.ndarray, jnp.ndarray, jnp.ndarray]:
        """Path geometry at arc-length s.

        Returns:
            x_r:   Cartesian x [...,]
            y_r:   Cartesian y [...,]
            θ_r:   heading angle [...,]
            κ_r:   curvature [...,]
        """
        raise NotImplementedError

    def evaluate_kappa_theta(self, s: jnp.ndarray) -> tuple[jnp.ndarray, jnp.ndarray]:
        """Lightweight: only heading and curvature at s.  Default: calls evaluate()."""
        _, _, θ_r, κ_r = self.evaluate(s)
        return θ_r, κ_r

    def frenet_to_cartesian(self, s: jnp.ndarray, d: jnp.ndarray) -> tuple[jnp.ndarray, jnp.ndarray]:
        """Convert Frenet (s, d) to Cartesian (x, y).

        x = x_r(s) - d · sin(θ_r(s))
        y = y_r(s) + d · cos(θ_r(s))
        """
        x_r, y_r, θ_r, _ = self.evaluate(s)
        x = x_r - d * jnp.sin(θ_r)
        y = y_r + d * jnp.cos(θ_r)
        return x, y

    def cartesian_to_frenet(self, x: jnp.ndarray, y: jnp.ndarray) -> tuple[jnp.ndarray, jnp.ndarray]:
        """Convert Cartesian (x, y) to Frenet (s, d). Inverse of frenet_to_cartesian.

        For general paths this requires solving the foot-of-perpendicular
        condition via 1D Newton.  The base class raises NotImplementedError;
        subclasses (including StraightReference) provide the implementation.
        """
        raise NotImplementedError


class StraightReference(ReferencePath):
    """Straight road aligned with x-axis: x=s, y=0, θ=0, κ=0."""

    def evaluate(self, s: jnp.ndarray) -> tuple[jnp.ndarray, jnp.ndarray, jnp.ndarray, jnp.ndarray]:
        x_r = s
        y_r = jnp.zeros_like(s)
        θ_r = jnp.zeros_like(s)
        κ_r = jnp.zeros_like(s)
        return x_r, y_r, θ_r, κ_r

    def frenet_to_cartesian(self, s: jnp.ndarray, d: jnp.ndarray) -> tuple[jnp.ndarray, jnp.ndarray]:
        # Straight road: x = s, y = d (no sin/cos needed)
        return s, d

    def cartesian_to_frenet(self, x: jnp.ndarray, y: jnp.ndarray) -> tuple[jnp.ndarray, jnp.ndarray]:
        # Straight road: s = x, d = y
        return x, y


class GeneralPath(ReferencePath):
    """General reference path from precomputed lookup table.

    Loads a .npz file generated by ``Cartest/basis/build_path.py`` containing
    (s, x, y, θ, κ) at uniform arc-length spacing.  Online operations are pure
    JAX table lookups — zero Python overhead after JIT.

    ``evaluate(s)``:   ``jnp.interp`` O(log N) interpolation.
    ``cartesian_to_frenet(x,y)``:  1D quasi-Newton on s, O(log N) per step,
                                    typically 1–3 iterations.
    """

    def __init__(self, table_path: str):
        import jax.numpy as jnp
        data = jnp.load(table_path)
        self._s_table = jnp.asarray(data["s"], dtype=jnp.float32)
        self._x_table = jnp.asarray(data["x"], dtype=jnp.float32)
        self._y_table = jnp.asarray(data["y"], dtype=jnp.float32)
        self._theta_table = jnp.asarray(data["theta"], dtype=jnp.float32)
        self._kappa_table = jnp.asarray(data["kappa"], dtype=jnp.float32)
        self._L = float(data["L"])
        self._ds = float(data["ds"])

    @property
    def L(self) -> float:
        return self._L

    def evaluate(self, s):
        """Full path geometry → (x_r, y_r, θ_r, κ_r).  4 table lookups."""
        s_clamped = jnp.clip(s, 0.0, self._L)
        x = jnp.interp(s_clamped, self._s_table, self._x_table)
        y = jnp.interp(s_clamped, self._s_table, self._y_table)
        theta = jnp.interp(s_clamped, self._s_table, self._theta_table)
        kappa = jnp.interp(s_clamped, self._s_table, self._kappa_table)
        return x, y, theta, kappa

    def evaluate_kappa_theta(self, s):
        """Lightweight: only heading and curvature.  2 table lookups."""
        s_clamped = jnp.clip(s, 0.0, self._L)
        theta = jnp.interp(s_clamped, self._s_table, self._theta_table)
        kappa = jnp.interp(s_clamped, self._s_table, self._kappa_table)
        return theta, kappa

    def cartesian_to_frenet(self, x, y):
        """1D quasi-Newton search for the closest-path-point → (s, d).

        Scalar inputs: runs Newton iteration via ``lax.while_loop``.
        Array inputs:  vmapped over leading dimensions.

        The objective is  f(s) = (x−x_r(s))² + (y−y_r(s))²  →  min_s.
        Since the path is arc-length parameterised, f″(s) ≈ 2 near the
        minimum, so a quasi-Newton step Δs = −f′(s)/2 is used.
        """
        import jax
        import jax.numpy as jnp
        from jax import lax

        s_arr = jnp.asarray(x)  # just to check if scalar
        if s_arr.ndim == 0:
            return self._cartesian_to_frenet_scalar(x, y)

        def _single(xi, yi):
            return self._cartesian_to_frenet_scalar(xi, yi)

        s_out, d_out = jax.vmap(_single)(x, y)
        return s_out, d_out

    def _cartesian_to_frenet_scalar(self, x, y):
        """Newton on a single (x, y) point."""
        import jax.numpy as jnp
        from jax import lax

        # ── Coarse grid search for initial guess ──
        n_coarse = 32
        idx = jnp.linspace(0, len(self._s_table) - 1, n_coarse, dtype=jnp.int32)
        s_coarse = self._s_table[idx]
        x_coarse = self._x_table[idx]
        y_coarse = self._y_table[idx]
        dist2 = (x - x_coarse) ** 2 + (y - y_coarse) ** 2
        s_init = s_coarse[jnp.argmin(dist2)]

        # ── Quasi-Newton iteration ──
        def _cond(state):
            _, _, _, _, itr, converged = state
            return jnp.logical_and(itr < 20, jnp.logical_not(converged))

        def _body(state):
            s_cur, _, _, _, itr, _ = state
            # Evaluate path at current s
            x_r = jnp.interp(s_cur, self._s_table, self._x_table)
            y_r = jnp.interp(s_cur, self._s_table, self._y_table)
            cos_t = jnp.cos(jnp.interp(s_cur, self._s_table, self._theta_table))
            sin_t = jnp.sin(jnp.interp(s_cur, self._s_table, self._theta_table))

            # f(s) = (x-x_r)² + (y-y_r)²
            # f′(s) = −2[(x−x_r)cosθ + (y−y_r)sinθ]
            dx = x - x_r
            dy = y - y_r
            grad = -2.0 * (dx * cos_t + dy * sin_t)
            # quasi-Newton: Δs = grad / 2  (f″ ≈ 2 for unit-speed curve)
            step = grad / 2.0
            s_new = jnp.clip(s_cur - step, 0.0, self._L)
            dist_new = jnp.sqrt(dx ** 2 + dy ** 2)

            # Convergence: step size < 1 mm
            converged = jnp.abs(step) < 1e-3
            return s_new, dist_new, grad, step, itr + 1, converged

        s_final, dist, grad, step, iters, _ = lax.while_loop(
            _cond,
            _body,
            (s_init, 1e9, 0.0, 1e9, 0, False),
        )

        # d = signed distance: positive = left of path (standard Frenet)
        x_r = jnp.interp(s_final, self._s_table, self._x_table)
        y_r = jnp.interp(s_final, self._s_table, self._y_table)
        theta_r = jnp.interp(s_final, self._s_table, self._theta_table)
        # Cross product: (x-x_r)·(-sinθ) + (y-y_r)·cosθ → sign
        cross = -(x - x_r) * jnp.sin(theta_r) + (y - y_r) * jnp.cos(theta_r)
        d = jnp.where(cross >= 0, dist, -dist)

        return s_final, d


class CircularReference(ReferencePath):
    """Circular reference path parameterized by arc length.

    s = 0 at the top (cx, cy + R), increasing counter-clockwise.
    Positive d = outside the circle (standard Frenet left-normal convention).
    """

    def __init__(self, R: float, cx: float = 0.0, cy: float = 0.0):
        self.R = R
        self.cx = cx
        self.cy = cy

    def evaluate(self, s: jnp.ndarray) -> tuple[jnp.ndarray, jnp.ndarray, jnp.ndarray, jnp.ndarray]:
        θ = s / self.R
        # s=0 at top (cx, cy+R), CCW:  x = R·sin(θ), y = R·cos(θ)
        # Tangent: (cos(θ), −sin(θ)) → heading = atan2(−sin, cos) = −θ (mod 2π)
        x_r = self.cx + self.R * jnp.sin(θ)
        y_r = self.cy + self.R * jnp.cos(θ)
        θ_r = -θ % (2 * jnp.pi)
        κ_r = jnp.full_like(s, 1.0 / self.R)
        return x_r, y_r, θ_r, κ_r

    def cartesian_to_frenet(self, x: jnp.ndarray, y: jnp.ndarray) -> tuple[jnp.ndarray, jnp.ndarray]:
        """Closed-form inverse for circles.

        s = R · atan2(x−cx, y−cy) mod 2πR  (swap x,y for sin/cos parameterization)
        d = √((x−cx)² + (y−cy)²) − R        (positive d = outside circle, Frenet convention)
        """
        dx = x - self.cx
        dy = y - self.cy
        angle = jnp.arctan2(dx, dy)         # swap: sin↔cos in parameterization
        angle = angle % (2 * jnp.pi)
        s = self.R * angle
        dist = jnp.sqrt(dx ** 2 + dy ** 2)
        d = dist - self.R                      # positive d = outside circle (Frenet convention)
        return s, d
